### ISSUE TITLE
Lack of Intuitive and Modern Design

### ISSUE THREAD

**Issue by James-Southgate** [BUAdvDev2023/resub-new-frontend#1]
The current user interface lacks intuitive and modern design principles. The design does not follow contemporary UI/UX standards, resulting in a dated and potentially frustrating user experience. Enhancements such as a clean, responsive layout, updated colour schemes, consistent typography, and improved navigation could significantly enhance usability and overall aesthetic appeal. Implementing these changes will help ensure the application meets modern user expectations and improves user satisfaction.

It would be good to try and have some consistency in the mobile storefront design and website design, could I assist in this?

**Comment by James-Southgate** [comment]
I am available to work on this whilst you work on connecting the backend server as you have mentioned in your README.md file

**Comment by s54BU** [comment]
Hi, sorry for the late reply but if you are able to improve the storefront design your contribution would be much appreciated
