### ISSUE TITLE
GDPR and Security Concerns

### ISSUE THREAD

**Issue by James-Southgate** [BUAdvDev2023/resub-new-frontend#2]
The repository currently lacks compliance with General Data Protection Regulation (GDPR) standards and exhibits several security vulnerabilities. Personal data handling practices are not clearly defined, and there are no measures in place to ensure data protection and user privacy. Additionally, the codebase lacks security features such as input validation, secure authentication mechanisms, and protection against common web vulnerabilities (e.g., XSS, CSRF). Addressing these issues is critical to protect user data, maintain regulatory compliance, and ensure the application's security and integrity.

**Comment by s54BU** [comment]
Hello James, 
Thank you so much for your feedback. I'm currently working on implementing input validation as well as securely storing personal information and will be posting an update soon

**Comment by s54BU** [comment]
I've just updated the repository. The project now has a backend and now has input validation as well as some means of data protection by hashing passwords. Unfortunately, protection against web vulnerabilities, particularly against CSRF, is so far limited but I believe it's a good foundation.
