### ISSUE TITLE
Bug found running with Docker

### ISSUE THREAD

**Issue by Treamas** [BUAdvDev2023/resub-new-frontend#3]
I got this issue when running the program with `docker compose up --build` and trying to access the program on http://localhost:8080.

![image](https://github.com/user-attachments/assets/16567045-6efd-4aac-a777-d870036a53ba)

The console in Docker produced this error '2024-07-30 11:34:01 [Tue Jul 30 10:34:01.539732 2024] [autoindex:error] [pid 19:tid 19] [client 172.18.0.1:59198] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive'.

I found by adding this code after line 20 on the Dockerfile I was able to run the website with Docker.

```dockerfile
# Set frontend_home.php as the default index file
RUN echo "DirectoryIndex frontend_home.php" > /etc/apache2/conf-available/directory-index.conf
RUN a2enconf directory-index

# Enable Apache rewrite module
RUN a2enmod rewrite

# Enable .htaccess files
RUN sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

# Create a .htaccess file to ensure proper routing
RUN echo "FallbackResource /frontend_home.php" > /var/www/html/.htaccess
```

Note: Took a few more seconds for the server to start running with this code added.

**Comment by s54BU** [comment]
I've been having the same issue and had to run the website by specifying the file that I want to open (by typing in `localhost:8080/frontend-home.php`)

Thank you for providing this code, I'll include it in the next update
